name: SkyShop
main: ru\universalcrew\formshop\Home
version: 2.0.0
api: 3.0.0-ALPHA11
author: Crafter@0162017
website: t.me/egr7v8
load: POSTWORLD
commands:
  shop:
    description: Command to access SkyRealmPE's Shop!
    permission: skyshop.command
   
    
